name: Telegram 5H Worker

on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          SOURCE_CHATS: ${{ secrets.SOURCE_CHATS }}
          TARGET_CHAT: ${{ secrets.TARGET_CHAT }}
        run: python app.py
